Specified support version
- typescript target ES2018
- node.js (>=10.15)

[Reason]

- ES2019 require node.js (>=12.4.0). So The supported version of node will be narrowed.
- Reason for choosing node 10.15 or higher.

```
node (v10.14.0)

    ReferenceError: beforeEach is not defined
      4 | import { inputFixturePath, outputFixturePath } from './utils';
      5 |
    > 6 | beforeEach(() => {
        | ^
      7 |   jest.spyOn(console, 'log').mockImplementation();
      8 |   jest.spyOn(console, 'warn').mockImplementation();
      9 | });
      at Object.<anonymous> (src/__tests__/basic.test.ts:6:1)

node (v10.9.0)
  TypeError: (0 , _vm(...).compileFunction) is not a function
      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1179:56)
```

[ref]
https://github.com/kulshekhar/ts-jest/issues/1764